### ISSUE TITLE
Invalid authorization code

### ISSUE THREAD

**Issue by fabianoaljava** [mageplaza/magento-2-instagram-feed#10]
Hi,

I did the whole instructions for getting the instagram feed access token like here: https://github.com/magepages/mpdocs/blob/master/docs/instagram-feed/2020-05-11-how-to-get-instagram-feed-access-token.md

However, I'm still getting the "Invalid authorization code" when I click on "Get your access code" on the module settings.

If I use the callback url with ?code=[MYSECRETTOKEN] works fine.

Any clues?

**Comment by Tuvpt** [comment]
Because you used the old version, the token could not be retrieved. We will release a new version soon

**Comment by MikeParkin** [comment]
@Tuvpt any update on this please?

**Comment by Tuvpt** [comment]
We have upgraded the module to apply changes to the API. You guys can experience it and please let me know the reviews
