### ISSUE TITLE
in version 1.1.0, can't see image resolution and on frontend settings dont

### ISSUE THREAD

**Issue by treesvalley** [mageplaza/magento-2-instagram-feed#12]
![insta](https://user-images.githubusercontent.com/32828416/85435509-fbac7680-b5a0-11ea-9e4f-e919bf91498f.png)

**Comment by toandt98** [comment]
Hello,

Currently this feature has not been integrated in the current version, we are trying to be compatible and bring it to the next version.
Hope that we will see it soon in the future!
