### ISSUE TITLE
Can not get Instagram data or your instagram account have not any images.

### ISSUE THREAD

**Issue by lucasltavares** [mageplaza/magento-2-instagram-feed#15]
I set the correct configuration but the block stills showing me this message: "Can not get Instagram data or your instagram account have not any images."

The token is correct too, any ideia of what may be causing this?

**Comment by Tuvpt** [comment]
Thank you for contacting us. I’m Curtis from Mageplaza Support Team.
Regarding your problem, please follow this guide to get access token
https://docs.mageplaza.com/instagram-feed/2020-05-11-how-to-get-instagram-feed-access-token.html

In addition, make sure you give full access when authenticating your account
