### ISSUE TITLE
Not Magento 2.4 Compatible

### ISSUE THREAD

**Issue by kestraly** [mageplaza/magento-2-instagram-feed#16]
Module required disabling otherwise 502 Nginx Error

**Comment by Tuvpt** [comment]
Hi @kestraly Thank you for your report.
To help us process this issue please make sure that you provided the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Please make sure that you install our core module

**Comment by kestraly** [comment]
After upgrading to Magento 2.4, Magento 2 would not initialise and gave an Nginx 502 with error 

**upstream sent too big header while reading response header from upstream**

Disabling the Instagram plugin resolved the issue.

To reproduce: Latest version of Instagram Plugin, upgrade from Magento 2.3.4 to Magento 2.4.0 via composer.

Entire website would not initialise frontend or backend.

**Comment by Tuvpt** [comment]
We apologize for any inconvenience.
We are unable to reproduce your problem.
Please contact us at support@mageplaza.com or livechat on our store
