### ISSUE TITLE
Module requires another module that links to a casino website.

### ISSUE THREAD

**Issue by cdbessig** [mageplaza/magento-2-instagram-feed#24]
https://github.com/mageplaza/magento-2-instagram-feed/blob/12197e1f19fd97e9bc2e4f1f8003408a84678040/composer.json#L6

Why does this module require: avada/module-proofo 

In the admin panel this gives us links to: https://proofo.io/?utm_source=github  which is an online casino site...

This looks very scammy and scares merchants into thinking their sites have been hacked.

**Comment by KhietNguyen83** [comment]
Hi @cdbessig ,
Thanks for your contribution.
We removed avada/module-proofo from composer.json and released in new version.
You can install the latest version.
Thank you very much!
