### ISSUE TITLE
Mageplaza / magento-2-instagram-feed integration

### ISSUE THREAD

**Issue by Bhumi04** [mageplaza/magento-2-instagram-feed#6]
Got below error:
{"meta": {"code": 400, "error_type": "OAuthAccessTokenException", "error_message": "The access_token provided is invalid."}}

I have followed all steps given on https://developers.facebook.com/docs/instagram-basic-display-api/getting-started

Can you please look into this?

**Comment by DrakeJack** [comment]
Please try to use the link
https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=code
You should replace the CLIENT-ID and REDIRECT-URI by your information to get the Code again.
Then you need to put the Code to the Code field to get the Access Token, maybe you used the Access token in other places so it needs to get the Redirect URL again.

**Comment by Bhumi04** [comment]
It gives below error:
{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: []"}

**Comment by Tuvpt** [comment]
We are really sorry for this problem.
Currently, we are looking for a solution to upgrade the module according to the new facebook API.
Therefore, the module will not be able to function normally. Please sympathize with us

**Comment by syedsaleem086** [comment]
Hi @Tuvpt 
Thanks for the update can you please let us know the estimated time for the new release

Thanks

**Comment by Tuvpt** [comment]
Hi @syedsaleem086 
We will notify you whenever there is a new update.
Thank you for your interest in our module

**Comment by DePalmo** [comment]
Hello,
I am aware that this is a free extension, but would like to know if you have any ETA of the fix for the mentioned bug.

**Comment by thegodfather78** [comment]
Do you have good news about a new release? Thanks

**Comment by Zyles** [comment]
Does this module not work anymore?

**Comment by Tuvpt** [comment]
We have upgraded the module to apply changes to the API. You guys can experience it and please let me know the reviews
