### ISSUE TITLE
Use new IG User Token Generator (Basic Display API)

### ISSUE THREAD

**Issue by LittleBigDev** [mageplaza/magento-2-instagram-feed#7]
Hello,
Did you plan to update this module so it uses the new Instagram User Token Generator (Basic Display API) ?

Their doc talks about short-lived (1h), long-lived (60 days) tokens and `/refresh_access_token` endpoint. 

Seems like the token needs to be periodically refreshed. I could not find anything like this in your module's source code.
What are your plans about this ?

**Comment by Tuvpt** [comment]
Thanks for your suggestions.
We are planning to update the module to the new Facebook API.
I haven't set a specific date yet, but it will be updated soon

**Comment by Tuvpt** [comment]
We have upgraded the module to apply changes to the API. You guys can experience it and please let me know the reviews
