### ISSUE TITLE
Instagram API is deprecated

### ISSUE THREAD

**Issue by jigar48** [mageplaza/magento-2-instagram-feed#8]
This module is not usable now because of Instagram API is deprecated and access token can not be generated from the Instagram account now.

**Comment by DrakeJack** [comment]
The issue above is because of the Instagram API has been changed.
We are updating the feature and compatible with the new API and update it soon.

**Comment by matteobaro** [comment]
any news of the update ?

**Comment by danrcoull** [comment]
any news on the update?

**Comment by arunu** [comment]
When will this updated version be released? BTW thanks for the free module !!

**Comment by Tuvpt** [comment]
We have updated the module with the new Facebook API. It will be released soon.

**Comment by davidwindell** [comment]
Thanks @Tuvpt !

**Comment by Tuvpt** [comment]
We have upgraded the module to apply changes to the API. You guys can experience it and please let me know the reviews
